### ISSUE TITLE
Sublime Text 3 with MacOS High Sierra

### ISSUE THREAD

**Issue by thomson** [randy3k/RemoteSubl#1]
I'm having an issue where I cannot open remote files in sublime text 3 (3143) with this package.

My `.ssh/config` is set with the ` RemoteForward 52698 localhost:52698` option.

I've installed the rsubl per your readme instruction on that remote server.

With Sublime Text 3 running, and issuing rsubl with verbose on the remote server seemingly shows that it times out.

If I open Textmate 2.0-rc4, then the rsubl remote command opens the remote file in Textmate.

On my local machine, with textmate running, doing a `telnet localhost 52698` connects. With Sublime Text 3 open and Textmate closed - running `telnet localhost 52698` does not connect.

**Comment by randy3k** [comment]
With textmate closed, could you restart sublime and check if the console has any messages related to RemoteSubl?

**Comment by thomson** [comment]
```
reloading plugin RemoteSubl.remote_subl
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "remote_subl in /Users/jesse/Library/Application Support/Sublime Text 3/Installed Packages/RemoteSubl.sublime-package", line 313, in plugin_loaded
  File "./python3.3/socketserver.py", line 430, in __init__
  File "./python3.3/socketserver.py", line 441, in server_bind
OSError: [Errno 48] Address already in use
```

**Comment by thomson** [comment]
With the address already in use error. I restarted my machine. Upon restart and viewing the console - I did not receive the error and your package is working as intended.

**Comment by randy3k** [comment]
Would it be possible that the port was used by textmate?

**Comment by thomson** [comment]
I did ensure that Textmate was closed and any connections/tunnels I had open were closed. Perhaps there was some zombie process or instance of something using that port for some reason - but I didn't investigate prior to restarting.
