### ISSUE TITLE
Connection refused on Server side

### ISSUE THREAD

**Issue by 18iteration** [randy3k/RemoteSubl#25]
Used rsuble/mate before and it worked though that was many months ago.
When I used it nowadays I get the error: 

```
/usr/local/bin/rsubl: connect: Connection refused
/usr/local/bin/rsubl: line 412: /dev/tcp/localhost/52698: Connection refused
Unable to connect to TextMate on localhost:52698

```
I allowed port 52698 in ufw (sudo ufw allow 52698). Rmate rsubl whatever its called is installed in Sublime on windows and running.
Important to note, I am running bitdefender on windows which has a nice firewall though I can't see it interfering.
Changed the SSH port to a custom one so I connect to the debian vps like this: 
`ssh -R 52698:localhost:52698 USER@IPADDRESS -pCUSTOMPORTNUMBER`

What am I missing? I am running windows 10, vps: debian 9.4. I looked through some issues here on github and couldn't fix it. Tried the Python version and couldn't fix it.
`netstat -tnl |grep 52698` returns nothing even with root.
EDIT: I shall add, that following the README.md Putty guide also doesn't work (same error with connection refused). 
EDIT EDIT: Just tried it all on a VM and it works, seems like the issue is with windows.

**Comment by randy3k** [comment]
I don't have any experiences with putty on Windows but I quite sure that it works according to some user reports.

**Comment by 18iteration** [comment]
@randy3k Hey thanks for replying to this issue.
I tried it with both cmd and putty. Same result. As noted in the edit edit, it works inside of a vm which is the decisive indication that this is an issue with windows or bitdefender.

**Comment by 18iteration** [comment]
Resolved, as mentioned above, this is a windows/my machine specific problem, rsubl works perfectly everywhere else. Thanks @randy3k for making this awesome imho must-have utility and your work.
