### ISSUE TITLE
Files containg line with string 'open' crashes

### ISSUE THREAD

**Issue by CRFSlick** [randy3k/RemoteSubl#27]
From what I understand, [rmate](https://github.com/aurora/rmate) uses regular characters in the format of keywords separated by colons to specify options over a socket connection. At some point, the 'data:'  keyword is encountered and everything after that should just be file data. 

I found that if a file contains the string 'open' on its own line with no other characters, that breaks the plugin and the file never opens on the remote instance of Sublime. The plugin continues treating the word 'open' as a special parameter even after data parsing had already started.

The fix is very easy, just check to see if data is already parsing before looking for the 'open' keyword, see #26

**Comment by randy3k** [comment]
thank for the report,
