### ISSUE TITLE
Ubuntu server to Win10 local

### ISSUE THREAD

**Issue by JuanFMontesinos** [randy3k/RemoteSubl#6]
Hi, is this supposed to work from a linux server to a win10 local machine?

I installed in a ubuntu 16 machine but I'm unable to see files on a windows 10 local machine.

**Comment by randy3k** [comment]
I remember that someone worked out how to use rmate over putty.

**Comment by JuanFMontesinos** [comment]
Hi, I was ussing python ssh and it seems it does not properly work with it. However putty worked.

Regards
